spring:
  application:
    name: mixedDemo
  datasource:
    username: wangtoye
    password: wangtoye
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: root
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8088

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/**/*.xml
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1